// ============================================================================
// Mesh (Portfolio) & Platform Templates
// ============================================================================

export function generateMeshYaml(
  name: string,
  org: string,
  owner: string,
  architectureDsl: string = 'calm',
  capabilityModel: string = 'insurance'
): string {
  const id = `PF-${org.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6)}-001`;
  return `# Initiative Mesh — generated by MaintainabilityAI Looking Glass
portfolio:
  id: ${id}
  name: "${name}"
  org: "${org}"
  owner: "${owner}"
  description: "Governance mesh for ${org}"

platforms: []

governance:
  review_cadence: quarterly
  maturity_target: 3
  architecture_dsl: ${architectureDsl}
  capability_model: ${capabilityModel}
  scoring:
    passing_threshold: 75
    warning_threshold: 50
`;
}

export function generateMeshReadme(name: string, org: string): string {
  return `# ${name}

> Governance mesh for **${org}** — managed by MaintainabilityAI Looking Glass

## Structure

\`\`\`
mesh.yaml                        # Portfolio definition (includes architecture_dsl)
platforms/                        # Platform groupings
  <platform>/
    platform.yaml                 # Platform metadata
    bars/                         # Business Application Repositories
      <app>/
        app.yaml                  # Application manifest
        architecture/             # Architecture as Code
          bar.arch.json           #   Unified CALM architecture (actors, systems, services, relationships, flows)
          decorator.json          #   CALM capability decorator (L1/L2/L3 business capabilities)
          ADRs/                   #   Architecture Decision Records
          fitness-functions.yaml  #   Automated quality gates
          quality-attributes.yaml #   Measurable quality scenarios
        security/                 # Application Security as Code
        information-risk/         # Information Risk as Code
        operations/               # Operations Governance as Code
        governance/               # Application-level decisions
policies/                         # Portfolio-level governance policies
governance/                       # Portfolio-level decisions
reports/                          # Generated reports
\`\`\`

> **Note:** When \`architecture_dsl: markdown\` is set in mesh.yaml, architecture artifacts use
> Markdown views (\`views/conceptual.md\`, \`logical.md\`, \`context.md\`, \`sequence.md\`) instead
> of CALM JSON files. The GovernanceScorer auto-detects the format.

## Four Governance Pillars

| Pillar | Purpose | Key Artifacts |
|--------|---------|---------------|
| Architecture | Structural integrity | CALM context/logical/decorator JSON, ADRs, fitness functions, quality attributes |
| Security | Application security posture | Threat models, security controls, vulnerability tracking |
| Information Risk | Data governance | Risk assessments, data classification, privacy impact |
| Operations | Operational readiness | Runbooks, service mapping, SLAs, incident response |

---

Generated by [MaintainabilityAI](https://maintainability.ai)
`;
}

export function generatePortfolioDecisionsYaml(): string {
  return `# Portfolio Governance Decisions
# Track portfolio-level architecture and governance decisions here
decisions: []
# Example:
#   - id: DEC-001
#     title: "Adopt event-driven architecture for inter-platform communication"
#     status: pending
#     date: "2026-02-17"
#     owner: ""
`;
}

// ============================================================================
// Policy Templates
// ============================================================================

export function generateArchitectureStandards(): string {
  return `# Architecture Standards
# Portfolio-level architecture conventions and constraints

fitness_functions:
  complexity:
    max_cyclomatic: 10
    description: "Functions must not exceed cyclomatic complexity of 10"
  coupling:
    max_afferent: 5
    description: "Modules should not have more than 5 inbound dependencies"

adr_requirements:
  minimum_per_bar: 1
  required_sections:
    - Status
    - Context
    - Decision
    - Consequences

views:
  required:
    - conceptual
    - context
  recommended:
    - logical
    - sequence
`;
}

export function generateSecurityBaseline(): string {
  return `# Security Baseline
# Minimum security requirements for all business applications

threat_modeling:
  methodology: STRIDE
  required: true
  review_cadence: quarterly

controls:
  authentication:
    required: true
    standards:
      - "Multi-factor authentication for privileged access"
      - "Session timeout <= 30 minutes"
  authorization:
    required: true
    standards:
      - "Deny-by-default access control"
      - "Principle of least privilege"
  encryption:
    data_at_rest: required
    data_in_transit: required
    standard: "AES-256 / TLS 1.2+"
  logging:
    security_events: required
    pii_masking: required

scanning:
  sast: required
  dependency: required
  cadence: "every PR"
`;
}

export function generateRiskFramework(): string {
  return `# Risk Framework
# Information risk classification and assessment criteria

data_classification:
  levels:
    - id: public
      label: Public
      description: "Information intended for public disclosure"
      controls: []
    - id: internal
      label: Internal
      description: "General business information"
      controls:
        - access_control
    - id: confidential
      label: Confidential
      description: "Sensitive business or customer data"
      controls:
        - access_control
        - encryption_at_rest
        - audit_logging
    - id: restricted
      label: Restricted
      description: "Highly sensitive data (PII, financial, health)"
      controls:
        - access_control
        - encryption_at_rest
        - encryption_in_transit
        - audit_logging
        - data_masking
        - retention_policy

assessment:
  required_artifacts:
    - ira
    - data_classification
    - vism
  review_cadence: semi-annual
`;
}

export function generateOperationsStandards(): string {
  return `# Operations Standards
# Operational readiness requirements for all business applications

runbook:
  required: true
  sections:
    - overview
    - architecture
    - deployment
    - monitoring
    - troubleshooting
    - contacts

service_mapping:
  required: true
  include:
    - upstream_dependencies
    - downstream_consumers
    - infrastructure_components

sla:
  required_for:
    - critical
    - high
  default_targets:
    availability: "99.9%"
    response_time_p95: "200ms"
    recovery_time: "4h"

incident_response:
  required: true
  include:
    - escalation_path
    - communication_plan
    - rollback_procedures
`;
}

// ============================================================================
// NIST SP 800-53 Controls Reference
// ============================================================================

export function generateNistControls(): string {
  return `# NIST SP 800-53 Controls Reference
# Curated subset for governance mesh threat model cross-referencing
# See: https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final
framework: "NIST SP 800-53 Rev 5"

families:
  - id: AC
    name: Access Control
    controls:
      - id: AC-1
        name: Policy and Procedures
        description: "Develop, document, and disseminate access control policy and procedures."
        priority: medium
      - id: AC-2
        name: Account Management
        description: "Manage system accounts including establishing, activating, modifying, reviewing, disabling, and removing accounts."
        priority: high
      - id: AC-3
        name: Access Enforcement
        description: "Enforce approved authorizations for logical access to information and system resources."
        priority: high
      - id: AC-6
        name: Least Privilege
        description: "Employ the principle of least privilege, allowing only authorized accesses necessary for users to accomplish assigned tasks."
        priority: high
      - id: AC-7
        name: Unsuccessful Logon Attempts
        description: "Enforce a limit of consecutive invalid logon attempts within a defined time period and automatically lock accounts."
        priority: medium

  - id: AU
    name: Audit and Accountability
    controls:
      - id: AU-2
        name: Event Logging
        description: "Identify events that the system is capable of logging in support of the audit function."
        priority: high
      - id: AU-3
        name: Content of Audit Records
        description: "Ensure audit records contain sufficient information to establish what occurred, when, where, and the source."
        priority: medium
      - id: AU-6
        name: Audit Record Review and Reporting
        description: "Review and analyze system audit records for indications of inappropriate or unusual activity."
        priority: medium
      - id: AU-12
        name: Audit Record Generation
        description: "Provide audit record generation capability for auditable events at system components."
        priority: high

  - id: CM
    name: Configuration Management
    controls:
      - id: CM-2
        name: Baseline Configuration
        description: "Develop, document, and maintain a current baseline configuration of the system."
        priority: medium
      - id: CM-6
        name: Configuration Settings
        description: "Establish and document mandatory configuration settings for IT products using security configuration checklists."
        priority: medium
      - id: CM-7
        name: Least Functionality
        description: "Configure the system to provide only mission-essential capabilities, prohibiting or restricting the use of unnecessary functions."
        priority: medium

  - id: CP
    name: Contingency Planning
    controls:
      - id: CP-2
        name: Contingency Plan
        description: "Develop a contingency plan for the system that identifies essential missions and business functions."
        priority: medium
      - id: CP-9
        name: System Backup
        description: "Conduct backups of user-level and system-level information contained in the system."
        priority: high
      - id: CP-10
        name: System Recovery and Reconstitution
        description: "Provide for the recovery and reconstitution of the system to a known state within defined time periods."
        priority: medium

  - id: IA
    name: Identification and Authentication
    controls:
      - id: IA-2
        name: Identification and Authentication (Organizational Users)
        description: "Uniquely identify and authenticate organizational users and associate that identity with processes acting on behalf of those users."
        priority: high
      - id: IA-5
        name: Authenticator Management
        description: "Manage system authenticators by verifying identity, establishing initial content, and ensuring administrative procedures."
        priority: high
      - id: IA-8
        name: Identification and Authentication (Non-Organizational Users)
        description: "Uniquely identify and authenticate non-organizational users or processes acting on behalf of non-organizational users."
        priority: medium

  - id: IR
    name: Incident Response
    controls:
      - id: IR-4
        name: Incident Handling
        description: "Implement an incident handling capability for incidents including preparation, detection, analysis, containment, eradication, and recovery."
        priority: high
      - id: IR-5
        name: Incident Monitoring
        description: "Track and document system security and privacy incidents."
        priority: medium
      - id: IR-6
        name: Incident Reporting
        description: "Require personnel to report suspected incidents to the organizational incident response capability within defined time periods."
        priority: medium

  - id: RA
    name: Risk Assessment
    controls:
      - id: RA-3
        name: Risk Assessment
        description: "Conduct an assessment of risk, including the likelihood and magnitude of harm, from unauthorized access, use, disclosure, or disruption."
        priority: high
      - id: RA-5
        name: Vulnerability Monitoring and Scanning
        description: "Monitor and scan for vulnerabilities in the system and hosted applications, and remediate discovered vulnerabilities."
        priority: high

  - id: SC
    name: System and Communications Protection
    controls:
      - id: SC-7
        name: Boundary Protection
        description: "Monitor and control communications at external managed interfaces, employing architectural designs and deny-by-default policies."
        priority: high
      - id: SC-8
        name: Transmission Confidentiality and Integrity
        description: "Protect the confidentiality and integrity of transmitted information using cryptographic mechanisms."
        priority: high
      - id: SC-12
        name: Cryptographic Key Establishment and Management
        description: "Establish and manage cryptographic keys when cryptography is employed within the system."
        priority: medium
      - id: SC-13
        name: Cryptographic Protection
        description: "Determine the required uses of cryptography and implement required cryptographic protections."
        priority: medium
      - id: SC-28
        name: Protection of Information at Rest
        description: "Protect the confidentiality and integrity of information at rest."
        priority: high

  - id: SI
    name: System and Information Integrity
    controls:
      - id: SI-2
        name: Flaw Remediation
        description: "Identify, report, and correct system flaws. Install security-relevant software and firmware updates within defined time periods."
        priority: high
      - id: SI-3
        name: Malicious Code Protection
        description: "Implement malicious code protection mechanisms at system entry and exit points to detect and eradicate malicious code."
        priority: medium
      - id: SI-4
        name: System Monitoring
        description: "Monitor the system to detect attacks and indicators of potential attacks, unauthorized connections, and activities."
        priority: high
      - id: SI-10
        name: Information Input Validation
        description: "Check the validity of information inputs to the system to prevent injection attacks and data corruption."
        priority: high

  - id: SA
    name: System and Services Acquisition
    controls:
      - id: SA-3
        name: System Development Life Cycle
        description: "Manage the system using a system development life cycle methodology that incorporates information security and privacy considerations."
        priority: medium
      - id: SA-11
        name: Developer Testing and Evaluation
        description: "Require the developer to create and implement a security and privacy assessment plan including flaw remediation and testing."
        priority: medium
`;
}

// ============================================================================
// Platform Templates
// ============================================================================

export function generatePlatformYaml(
  id: string,
  name: string,
  portfolioId: string,
  owner: string
): string {
  return `# Platform definition — generated by MaintainabilityAI Looking Glass
platform:
  id: ${id}
  name: "${name}"
  portfolio: ${portfolioId}
  owner: "${owner}"
  description: ""
`;
}

export function generatePlatformDecisionsYaml(): string {
  return `# Platform Governance Decisions
decisions: []
`;
}
