import * as fs from 'fs';
import * as path from 'path';
import type { TechStack } from '../types';
import { serializeMetadataYaml, type RepoMetadata } from '../services/RepoMetadata';

// ============================================================================
// HELPERS
// ============================================================================

/** Read a file from the extension's code-templates directory. */
function readScaffoldFile(extensionPath: string, ...segments: string[]): string {
  const filePath = path.join(extensionPath, 'code-templates', ...segments);
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
}

export function generateClaudeMd(stack: TechStack): string {
  return `# CLAUDE.md

This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.

## Project Overview

**Tech Stack**: ${stack.language}, ${stack.runtime}, ${stack.framework}
**Database**: ${stack.database}
**Testing**: ${stack.testing}
**Validation**: ${stack.validation}
**CI/CD**: ${stack.cicd}

## Security Framework

This project follows the MaintainabilityAI security-first SDLC framework:
- OWASP Top 10 prompt packs for security guidance
- STRIDE threat modeling for design reviews
- Fitness functions for automated quality gates
- Golden Rules of Vibe Coding for governance

## Development Commands

\`\`\`bash
# Install dependencies
npm install

# Run tests
npm test

# Lint
npm run lint

# Build
npm run build
\`\`\`

## Security Workflow

1. **Be specific** — Define intent and security constraints in prompts
2. **Trust but verify** — Never merge AI-generated code without understanding it
3. **Treat AI like a junior dev** — Review, guide, and validate suggestions
4. **Isolate AI changes** — Use separate commits/PRs; label AI-assisted changes
5. **Document rationale** — Explain the "why" in code comments and commit messages
6. **Share winning prompts** — Capture effective prompts in \`/prompts\` for reuse

## Commit Labeling

Always use the AI disclosure label in commits:
\`\`\`bash
git commit -m "feat: Add user authentication

🤖 AI-assisted with [tool] using MaintainabilityAI prompt packs"
\`\`\`

---

Generated by MaintainabilityAI VS Code Extension
`;
}

export function generatePrTemplate(): string {
  return `## Summary

<!-- Brief description of changes -->

## Changes

<!-- List of changes made -->

## Security Checklist

- [ ] No new security vulnerabilities introduced
- [ ] Input validation added for all user inputs
- [ ] Error handling does not leak sensitive information
- [ ] Tests cover security-relevant code paths
- [ ] Dependencies are up to date and free of known CVEs

## AI Disclosure

- [ ] This PR includes AI-assisted code
- **Tool(s) used**: <!-- Claude Code / Copilot / ChatGPT -->
- **Prompt pack(s)**: <!-- OWASP A03, Maintainability/complexity-reduction, etc. -->

## Testing

\`\`\`bash
npm test
# All tests passing ✓
\`\`\`

---

🤖 Generated with [MaintainabilityAI](https://maintainability.ai)
`;
}

export function generateSecurityPolicy(): string {
  return `# Security Policy

## Reporting a Vulnerability

If you discover a security vulnerability, please report it responsibly:

1. **Do not** create a public GitHub issue
2. Email security concerns to the repository maintainers
3. Include steps to reproduce the vulnerability
4. Allow reasonable time for a fix before public disclosure

## Supported Versions

| Version | Supported |
|---------|-----------|
| Latest  | ✅        |

## Security Practices

This project follows the MaintainabilityAI security-first framework:
- OWASP Top 10 compliance checks
- Automated security scanning (CodeQL, Snyk)
- Fitness functions for quality gates
- AI-assisted development with human oversight

---

Generated by MaintainabilityAI VS Code Extension
`;
}

export function generateAliceRemediationWorkflow(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'alice-remediation.yml');
}

export function generateCopilotSetupSteps(stack: TechStack, extensionPath: string): string {
  const cmds = getStackCommands(stack);
  let yml = readScaffoldFile(extensionPath, 'workflows', 'copilot-setup-steps.yml');

  // getStackCommands() returns setup strings with 6-space indent (for nested workflow YAML).
  // copilot-setup-steps.yml uses 2-space indent under `steps:`, so strip the extra 4 spaces.
  const setup = cmds.setup.replace(/^ {6}/gm, '  ');
  yml = yml.replace(/\{\{SETUP_STEPS\}\}/g, setup);
  yml = yml.replace(/\{\{INSTALL_CMD\}\}/g, cmds.install);

  // Add extra setup for test frameworks that download binaries at runtime
  const testing = stack.testing?.toLowerCase() || '';
  let extra = '';
  if (testing === 'mocha' || testing === 'jest') {
    // Pre-download MongoMemoryServer binary if mongodb-memory-server is a dependency.
    // This runs BEFORE the firewall, so the binary download from fastdl.mongodb.org works.
    // Uses the actual MongoBinary API to trigger the download (no CLI --download-only flag exists).
    extra += '  - name: Pre-cache MongoDB binary (for MongoMemoryServer)\n';
    extra += '    run: |\n';
    extra += '      if grep -q "mongodb-memory-server" package.json 2>/dev/null; then\n';
    extra += '        node -e "const { MongoBinary } = require(\'mongodb-memory-server-core\'); MongoBinary.getPath({}).then(p => console.log(\'MongoDB binary cached at:\', p)).catch(e => console.error(\'Download failed:\', e.message))"\n';
    extra += '      fi\n';
    extra += '    continue-on-error: true\n';
  }
  yml = yml.replace(/\{\{EXTRA_SETUP\}\}/g, extra);
  return yml;
}

export function generateCodeqlWorkflow(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'codeql.yml');
}

export function generateFitnessFunctionsWorkflow(stack: TechStack, extensionPath: string): string {
  const cmds = getStackCommands(stack);
  let yml = readScaffoldFile(extensionPath, 'workflows', 'fitness-functions.yml');
  yml = yml.replace(/\{\{SETUP_STEPS\}\}/g, cmds.setup);
  yml = yml.replace(/\{\{INSTALL_CMD\}\}/g, cmds.install);
  yml = yml.replace(/\{\{TEST_COVERAGE_CMD\}\}/g, cmds.testCoverage);
  yml = yml.replace(/\{\{TEST_FITNESS_CMD\}\}/g, cmds.testFitness);
  return yml;
}

// ============================================================================
// STACK-AWARE CI WORKFLOW
// ============================================================================

function getStackCommands(stack: TechStack): {
  setup: string;
  install: string;
  test: string;
  testCoverage: string;
  testFitness: string;
  testJson: string;
  envSetup: string;
  lintStep: string;
} {
  const lang = stack.language?.toLowerCase() || '';
  const pm = stack.packageManager?.toLowerCase() || 'npm';
  const testing = stack.testing?.toLowerCase() || '';

  if (lang === 'python') {
    const hasPyproject = stack.runtime?.includes('pyproject');
    const pyManifest = hasPyproject ? 'pyproject.toml' : 'requirements.txt';
    const pyInstall = hasPyproject ? 'pip install -e ".[dev]"' : 'pip install -r requirements.txt';
    return {
      setup: '      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.12"',
      install: `if [ -f ${pyManifest} ]; then ${pyInstall}; fi`,
      test: `if [ -f ${pyManifest} ]; then pytest --tb=short; fi`,
      testCoverage: 'pytest --cov --tb=short',
      testFitness: 'pytest tests/fitness_functions/ --tb=short',
      testJson: `if [ -f ${pyManifest} ]; then pytest --tb=short --junitxml=test-results.xml 2>&1 | tee test-output.txt; fi`,
      envSetup: '',
      lintStep: `      - name: Lint\n        run: if [ -f ${pyManifest} ]; then pip install ruff && ruff check .; fi`,
    };
  }

  if (lang === 'go') {
    return {
      setup: '      - uses: actions/setup-go@v5\n        with:\n          go-version: "1.22"',
      install: 'if [ -f go.mod ]; then go mod download; fi',
      test: 'if [ -f go.mod ]; then go test ./...; fi',
      testCoverage: 'go test ./... -cover',
      testFitness: 'go test ./tests/fitness-functions/...',
      testJson: 'if [ -f go.mod ]; then go test ./... -json 2>&1 | tee test-output.txt; fi',
      envSetup: '',
      lintStep: '',
    };
  }

  if (lang === 'rust') {
    return {
      setup: '      - uses: dtolnay/rust-toolchain@stable',
      install: 'if [ -f Cargo.toml ]; then cargo fetch; fi',
      test: 'if [ -f Cargo.toml ]; then cargo test; fi',
      testCoverage: 'cargo test',
      testFitness: 'cargo test fitness',
      testJson: 'if [ -f Cargo.toml ]; then cargo test -- --format json 2>&1 | tee test-output.txt; fi',
      envSetup: '',
      lintStep: '      - name: Lint\n        id: lint\n        run: if [ -f Cargo.toml ]; then cargo clippy -- -D warnings 2>&1 | tee lint-output.txt; fi\n        continue-on-error: true',
    };
  }

  // Default: Node.js (JavaScript / TypeScript)
  // Use fallback pattern (strict || lenient) so CI works before a lockfile exists
  let setup = '      - uses: actions/setup-node@v4\n        with:\n          node-version: 20';
  let install = 'if [ -f package.json ]; then npm ci || npm install; fi';
  let testCmd = 'if [ -f package.json ]; then npm test; fi';
  let testCov = 'npm test -- --coverage';
  let testFit = 'npm test tests/fitness-functions/';
  let testJson = 'if [ -f package.json ]; then npm test -- --json --outputFile=test-results.json 2>&1 | tee test-output.txt; fi';
  let lintStep = '      - name: Lint\n        id: lint\n        run: if [ -f package.json ]; then npm run lint --if-present 2>&1 | tee lint-output.txt; fi\n        shell: bash\n        continue-on-error: true';

  if (pm === 'pnpm') {
    setup += '\n      - uses: pnpm/action-setup@v4\n        with:\n          version: 9';
    install = 'if [ -f package.json ]; then pnpm install --frozen-lockfile || pnpm install; fi';
    testCmd = 'if [ -f package.json ]; then pnpm test; fi';
    testCov = 'pnpm test -- --coverage';
    testFit = 'pnpm test tests/fitness-functions/';
    testJson = 'if [ -f package.json ]; then pnpm test -- --json --outputFile=test-results.json 2>&1 | tee test-output.txt; fi';
    lintStep = '      - name: Lint\n        id: lint\n        run: if [ -f package.json ]; then pnpm run lint --if-present 2>&1 | tee lint-output.txt; fi\n        shell: bash\n        continue-on-error: true';
  } else if (pm === 'yarn') {
    install = 'if [ -f package.json ]; then yarn install --frozen-lockfile || yarn install; fi';
    testCmd = 'if [ -f package.json ]; then yarn test; fi';
    testCov = 'yarn test --coverage';
    testFit = 'yarn test tests/fitness-functions/';
    testJson = 'if [ -f package.json ]; then yarn test --json --outputFile=test-results.json 2>&1 | tee test-output.txt; fi';
    lintStep = '      - name: Lint\n        id: lint\n        run: if [ -f package.json ]; then yarn run lint --if-present 2>&1 | tee lint-output.txt; fi\n        shell: bash\n        continue-on-error: true';
  } else if (pm === 'bun') {
    setup = '      - uses: oven-sh/setup-bun@v2';
    install = 'if [ -f package.json ]; then bun install; fi';
    testCmd = 'if [ -f package.json ]; then bun test; fi';
    testCov = 'bun test';
    testFit = 'bun test tests/fitness-functions/';
    testJson = 'if [ -f package.json ]; then bun test 2>&1 | tee test-output.txt; fi';
    lintStep = '      - name: Lint\n        id: lint\n        run: if [ -f package.json ]; then bun run lint 2>&1 | tee lint-output.txt; fi\n        shell: bash\n        continue-on-error: true';
  }

  // Vitest uses different flags
  if (testing === 'vitest') {
    const runner = pm === 'pnpm' ? 'pnpm' : pm === 'yarn' ? 'yarn' : pm === 'bun' ? 'bun' : 'npx';
    testJson = `if [ -f package.json ]; then ${runner} vitest run --reporter=json --outputFile=test-results.json 2>&1 | tee test-output.txt; fi`;
    testCov = `${runner} vitest run --coverage`;
  } else if (testing === 'mocha') {
    const runner = pm === 'pnpm' ? 'pnpm exec' : pm === 'yarn' ? 'yarn' : 'npx';
    testJson = `if [ -f package.json ]; then ${runner} mocha --exit --reporter json 2>&1 | tee test-output.txt; fi`;
  }

  return {
    setup,
    install,
    test: testCmd,
    testCoverage: testCov,
    testFitness: testFit,
    testJson,
    envSetup: '      - run: cp .env.example .env 2>/dev/null || true',
    lintStep,
  };
}

export function generateCiWorkflow(stack: TechStack, extensionPath: string): string {
  const cmds = getStackCommands(stack);
  const lang = stack.language?.toLowerCase() || '';

  const failureScriptFile = lang === 'python' ? 'ci-failure-handler-python.js' : 'ci-failure-handler-node.js';
  let yml = readScaffoldFile(extensionPath, 'workflows', 'ci.yml');
  const failureScript = readScaffoldFile(extensionPath, 'scripts', failureScriptFile);
  const closeScript = readScaffoldFile(extensionPath, 'scripts', 'ci-success-closer.js');

  // Replace tokens
  yml = yml.replace(/\{\{SETUP_STEPS\}\}/g, cmds.setup);
  yml = yml.replace(/\{\{INSTALL_CMD\}\}/g, cmds.install);
  yml = yml.replace(/\{\{TEST_CMD\}\}/g, cmds.testJson);
  yml = yml.replace(/\{\{ENV_SETUP\}\}/g, cmds.envSetup || '');
  yml = yml.replace(/\{\{LINT_STEP\}\}/g, cmds.lintStep || '');
  yml = yml.replace(/\{\{FAILURE_SCRIPT\}\}/g, failureScript.split('\n').map((l, i) => i === 0 ? l : '            ' + l).join('\n'));
  yml = yml.replace(/\{\{CLOSE_SCRIPT\}\}/g, closeScript.split('\n').map((l, i) => i === 0 ? l : '            ' + l).join('\n'));

  return yml;
}

export function generateRepoMetadata(stack: TechStack, modelFamily?: string): string {
  const moduleSystem = stack.runtime?.includes('ESM') || stack.runtime?.includes('Vite') ? 'ESM' : 'CommonJS';
  const meta: RepoMetadata = {
    language: stack.language || undefined,
    module_system: stack.language?.toLowerCase() === 'python' ? undefined : moduleSystem,
    testing: stack.testing || undefined,
    package_manager: stack.packageManager || undefined,
    framework: stack.framework || undefined,
    database: stack.database || undefined,
  };
  if (modelFamily) {
    meta.llm = { model_family: modelFamily };
  }
  return serializeMetadataYaml(meta);
}

export function generateCodeqlToIssuesWorkflow(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'codeql-to-issues.yml');
}

export function generateValidatePromptHashesWorkflow(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'validate-prompt-hashes.yml');
}


export function generatePromptMappings(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'scripts', 'prompt-mappings.json');
}

export function generatePromptHashGenerator(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'scripts', 'generate-prompt-hashes.cjs');
}

export function generateProcessCodeqlResults(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'scripts', 'process-codeql-results.cjs');
}

// ============================================================================
// Oraculum Templates
// ============================================================================

export function generateOraculumWorkflow(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'oraculum-review.yml');
}

// ============================================================================
// Mesh Workflows — Research + PRD Agent Pipeline (Caterpillar / Looking Glass)
// ============================================================================
//
// Per-workflow `generate<Name>Workflow` helpers (oraculum-research,
// archeologist, prd, label-on-merge, notify-code-repos, pr-auto-label)
// were removed once MESH_WORKFLOWS centralized the registry and the
// consolidated per-agent workflows (B20: market-research-agent.yml,
// prd-agent.yml) replaced the older single-purpose YAMLs. Deployment
// reads from MESH_WORKFLOWS via readScaffoldFile directly — no per-file
// generator stub is needed. `pruneDeprecatedWorkflows` handles cleanup
// of any stale copies left in mesh repos.

/**
 * Phase B20 — `market-research-agent.yml` is the agent-keyed
 * consolidation for the WHY phase. Single workflow file with three
 * jobs (dispatch on issue, audit-and-drift on user-applied
 * `research-synthesis` label, finalize on merge) replacing the
 * WHY-phase branches of okr-bus.yml + audit-validate.yml +
 * drift-gate.yml + pr-auto-label.yml.
 *
 * Depends on three composite actions under `.github/actions/`:
 *   - extract-okr-context (parse Hatter Tag from PR body)
 *   - count-skill-calls (per-provider audit count + distinct queries)
 *   - check-tier-bound (tier → MAX_AUTO_ROUNDS resolution)
 *
 * See agentic-sdlc.md §13 B20.
 */
export function generateMarketResearchAgentWorkflow(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'market-research-agent.yml');
}

/**
 * Per-agent workflow for the prd-agent (HOW phase) — Phase 2 of B20.
 * Owns dispatch on `oraculum-prd` issues + audit-and-drift on
 * `prd-draft` PRs + finalize on PR merge.
 *
 * Audit checks: evidence honesty (mesh skill_call counts), structural
 * correctness (10 H2 sections + FR-NN/SR-NN citation coverage), Pocket
 * Watch (OKR objective vs prd.md Problem Statement), Caterpillar's
 * Challenge (PRD Problem Statement vs research-doc Executive Summary
 * — first cross-phase drift gate in the pipeline).
 *
 * Replaces (for the HOW scope) okr-bus / audit-validate / drift-gate.
 */
export function generatePrdAgentWorkflow(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'prd-agent.yml');
}

/**
 * Per-agent workflow for the code-design-agent (WHAT phase) — D-PR1 MVP.
 * Owns dispatch on `oraculum-design` issues + audit-and-drift on
 * `design-draft` PRs + finalize on PR merge.
 *
 * Audit checks: chain integrity (B25), Knight's Seal (B27), per-repo
 * mode honesty (A12.v1.1 — knowledge-code chain mode matches code-
 * design.md per-repo frontmatter mode), self-review block/chain
 * reconciliation (B28c.v1.1 pattern with B29 fallback for code-* personas).
 *
 * Dispatch precondition: A12.v1.1 — every targetCodeRepos[] entry's
 * status MUST be 'connected' or 'create' before the agent runs. Any
 * 'not-connected' / 'unreachable' entry blocks dispatch with a comment.
 *
 * Pocket Watch + Caterpillar drift gates are report-only in D-PR1 MVP;
 * thresholds calibrate in D-PR1.v1.1 after the first end-to-end run.
 */
export function generateCodeDesignAgentWorkflow(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'code-design-agent.yml');
}

// architect-reviewer.yml + security-reviewer.yml removed in B24 —
// self-critique inside prd-agent.agent.md (Architect + Security
// personas, bounded rounds) replaced the separate reviewer dispatches.
// The deleted workflow paths land in DEPRECATED_MESH_FILES below so
// pruneDeprecatedWorkflows sweeps them on next Redeploy.

/**
 * Composite action: extract okr_id/run_id/phase/intent_thread_uuid/
 * evidence_mode/fresh_provider_search_performed/author_did from a PR
 * body's Hatter Tag block. Used by every per-agent workflow's
 * audit-and-drift + finalize jobs to read the OKR identity off a PR.
 */
export function generateExtractOkrContextAction(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'actions', 'extract-okr-context', 'action.yml');
}

/**
 * Composite action: count successful skill_call events per search
 * provider + collect distinct-query counts from an audit JSONL.
 * Used by every per-agent workflow's audit-and-drift job.
 */
export function generateCountSkillCallsAction(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'actions', 'count-skill-calls', 'action.yml');
}

/**
 * Composite action: resolve frozen governanceTier + MAX_AUTO_ROUNDS
 * for a given OKR action by runId. Used by prd-agent + code-design-
 * agent state-machine jobs (revision-escalation, HumanGate transitions).
 */
export function generateCheckTierBoundAction(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'actions', 'check-tier-bound', 'action.yml');
}

/**
 * Composite action: canonical finalize body shared across all three
 * per-agent workflows (WHY / HOW / WHAT). Refactor 3c eliminated the
 * "5 ways to finalize" smell by consolidating: yq-based action status
 * flip + completedAt + hatterChainRoot write + meta.status forward-
 * roll + chain-ladder append + commit-and-push retry loop. Each
 * workflow delegates via `uses: ./.github/actions/finalize-okr-action`
 * with phase-specific inputs (phase + current-meta-status +
 * next-meta-status + prior-phase). See phaseSpec.ts for the canonical
 * input values per phase.
 */
export function generateFinalizeOkrAction(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'actions', 'finalize-okr-action', 'action.yml');
}

/**
 * Node script invoked by finalize-okr-action — appends durable workflow
 * events (artifact_written + state_transition) to the per-run audit
 * JSONL with idempotency + verify-before-commit semantics. Bug Z/4:
 * PR audit verifies; finalize records. This script is the only durable
 * workflow-event writer in the system.
 */
export function generateAppendWorkflowEventsScript(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'actions', 'finalize-okr-action', 'scripts', 'append-workflow-events.mjs');
}

/**
 * Node script invoked by market-research-agent.yml audit job — verifies
 * every S[N] citation in research-doc.md matches a (title, url) preview
 * from the audited chain. Bug Z/2: WHY-phase evidence-laundering check.
 */
export function generateVerifySourceTableScript(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'scripts', 'verify-source-table.mjs');
}

/**
 * Oracle & Privacy Rails (Phase 2) — trusted PII-rail helpers fetched by
 * market-research-agent.yml (PR gate) + the WHY finalize job, and replayed by
 * oracle-rails-replay.yml. The rail fails CLOSED if these aren't on the default
 * branch, so they MUST be in the canonical deploy set (this is the file set the
 * "redeploy mesh workflows" gap missed). Read verbatim — no substitution.
 */
export function generateOracleRailsReplayWorkflow(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'oracle-rails-replay.yml');
}
export function generateOracleRailScript(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'scripts', 'oracle-rails', 'oracle_rail.py');
}
export function generateOracleRailConfig(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'scripts', 'oracle-rails', 'pii.json');
}
export function generateOracleRailRequirements(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'scripts', 'oracle-rails', 'requirements.txt');
}

/**
 * Oracle & Privacy Rails (Phase 3) — INJECTION rail (Llama Prompt Guard 2 86M).
 * Same trust model as the PII rail: fetched from the default branch by the PR
 * gate + WHY finalize, replayed by oracle-rails-replay.yml. Fails CLOSED when
 * absent, so these MUST be in the canonical deploy set. Read verbatim.
 */
export function generateOracleInjectionScript(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'scripts', 'oracle-rails', 'inject_check.py');
}
export function generateOracleInjectionConfig(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'scripts', 'oracle-rails', 'injection.json');
}
/**
 * Oracle injection rail CERT (Phase 3 step 5b) — a manual workflow_dispatch job
 * that runs the DEPLOYED rail over inline hostile + benign fixtures and asserts
 * exit-code (hostile non-pass, benign pass). Deployed so the cert runs against
 * the mesh's own copy of the rail; never auto-triggers (dispatch only).
 */
export function generateOracleInjectionCertWorkflow(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'oracle-injection-cert.yml');
}
/**
 * Oracle & Privacy Rails (Phase 4) — GROUNDEDNESS rail (NLI cross-encoder).
 * Same fail-closed / replay-verified contract as the PII + injection rails:
 * fetched from the default branch by the PR gate + WHY finalize, replayed by
 * oracle-rails-replay.yml. Ships advisory first. Read verbatim.
 */
export function generateOracleGroundednessScript(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'scripts', 'oracle-rails', 'groundedness.py');
}
export function generateOracleGroundednessConfig(extensionPath: string): string {
  return readScaffoldFile(extensionPath, 'workflows', 'scripts', 'oracle-rails', 'groundedness.json');
}

/**
 * Canonical list of every workflow Looking Glass writes into the mesh repo's
 * .github/workflows/ directory. Order is deterministic — used for both write
 * and existence checks so the UI's deployed/not-deployed state is consistent.
 */
export interface MeshWorkflowSpec {
  /** Relative path inside the mesh repo, e.g. ".github/workflows/archeologist.yml" */
  relativePath: string;
  /** Generator that returns the file contents */
  generate: (extensionPath: string) => string;
}

export const MESH_WORKFLOWS: MeshWorkflowSpec[] = [
  // ── BAR-page domain (separate from agentic-SDLC) ─────────────────────
  { relativePath: '.github/workflows/oraculum-review.yml',   generate: generateOraculumWorkflow },

  // ── Phase B20 per-agent workflows ────────────────────────────────────
  // market-research-agent owns the complete WHY phase (Phase 1 — shipped).
  // prd-agent owns the complete HOW phase, including self-critique
  // rounds — separate architect/security reviewer agents were removed
  // in B24 because at PRD time they re-graded the same mesh state the
  // author already used (no independent evidence surface). Code-design-
  // agent lands in Phase 3 for WHAT.
  { relativePath: '.github/workflows/market-research-agent.yml', generate: generateMarketResearchAgentWorkflow },
  { relativePath: '.github/workflows/prd-agent.yml',             generate: generatePrdAgentWorkflow },
  // D-PR1 — code-design-agent for the WHAT phase. Brownfield/greenfield
  // branching per A12.v1.1 targetCodeRepoStatus.
  { relativePath: '.github/workflows/code-design-agent.yml',     generate: generateCodeDesignAgentWorkflow },

  // ── Composite actions (referenced by per-agent workflows) ────────────
  { relativePath: '.github/actions/extract-okr-context/action.yml', generate: generateExtractOkrContextAction },
  { relativePath: '.github/actions/count-skill-calls/action.yml',   generate: generateCountSkillCallsAction },
  { relativePath: '.github/actions/check-tier-bound/action.yml',    generate: generateCheckTierBoundAction },
  // Refactor 3c — canonical finalize body shared by all per-agent workflows.
  { relativePath: '.github/actions/finalize-okr-action/action.yml',  generate: generateFinalizeOkrAction },
  // Bug Z/4 — durable workflow-event writer (artifact_written + state_transition)
  // with idempotency + verify-before-commit. Invoked by finalize-okr-action.
  { relativePath: '.github/actions/finalize-okr-action/scripts/append-workflow-events.mjs', generate: generateAppendWorkflowEventsScript },
  // Bug Z/2 — WHY-phase source-claim integrity check (S[N] title+url vs
  // chain results_preview[]). Invoked by market-research-agent.yml audit.
  { relativePath: '.github/workflows/scripts/verify-source-table.mjs', generate: generateVerifySourceTableScript },

  // ── Oracle & Privacy Rails (Phase 2) — PII rail (Hatter-side) ────────
  // The rail helpers are fetched from the default branch by the PR gate +
  // WHY finalize, and the rail FAILS CLOSED when absent — so they MUST be in
  // the canonical deploy set. (Redeploy gap: these were missing, so the gate
  // reported "Oracle PII rail helpers not deployed".)
  { relativePath: '.github/workflows/oracle-rails-replay.yml',                  generate: generateOracleRailsReplayWorkflow },
  { relativePath: '.github/workflows/scripts/oracle-rails/oracle_rail.py',      generate: generateOracleRailScript },
  { relativePath: '.github/workflows/scripts/oracle-rails/pii.json',            generate: generateOracleRailConfig },
  { relativePath: '.github/workflows/scripts/oracle-rails/requirements.txt',    generate: generateOracleRailRequirements },

  // ── Oracle & Privacy Rails (Phase 3) — injection rail (Prompt Guard 2) ─
  // Same fail-closed contract as the PII rail above. inject_check.py shares
  // requirements.txt with oracle_rail.py (both pip-installed by the workflow),
  // so only the script + its config deploy here.
  { relativePath: '.github/workflows/scripts/oracle-rails/inject_check.py',     generate: generateOracleInjectionScript },
  { relativePath: '.github/workflows/scripts/oracle-rails/injection.json',      generate: generateOracleInjectionConfig },
  // Cert (5b) — manual dispatch only; runs the deployed rail over fixtures.
  { relativePath: '.github/workflows/oracle-injection-cert.yml',                generate: generateOracleInjectionCertWorkflow },

  // ── Oracle & Privacy Rails (Phase 4) — groundedness rail (NLI) ─────────
  // Same fail-closed / replay contract; shares requirements.txt (transformers +
  // torch + sentencepiece). Ships advisory until the cert pins the NLI model.
  { relativePath: '.github/workflows/scripts/oracle-rails/groundedness.py',     generate: generateOracleGroundednessScript },
  { relativePath: '.github/workflows/scripts/oracle-rails/groundedness.json',   generate: generateOracleGroundednessConfig },

  // No transitional workflows remain. WHY + HOW + WHAT are owned end-
  // to-end by per-agent workflows above. The prior bus / state-machine
  // / drift-gate / audit-validate workflows have been removed (added
  // to DEPRECATED_MESH_FILES below so pruneDeprecatedWorkflows sweeps
  // them from any mesh repo on next Redeploy).
  //
  // design-bus.yml (formerly queued as D-PR4 workflow) was superseded
  // — D-PR4 shipped as an app-side fan-out engine in Looking Glass
  // (per `vscode-extension/design/next-acts-tier-2-and-3.md`). The
  // deprecated entry below in DEPRECATED_MESH_FILES stays so
  // pruneDeprecatedWorkflows sweeps any prior-installed copies from
  // mesh repos on next Redeploy. (Codex-r1 Bug I — comment cleanup.)
];

/**
 * Files we used to deploy but no longer do — `pruneDeprecatedWorkflows`
 * deletes any of these that still exist in the mesh repo on next
 * "Redeploy Workflows" click. This is how Looking Glass keeps the mesh
 * `.github/workflows/` tree clean as the per-agent consolidation rolls
 * out incrementally.
 *
 * Add to this list whenever an entry is removed from MESH_WORKFLOWS.
 * Never remove an entry once added (idempotent prune semantics).
 */
export const DEPRECATED_MESH_FILES: string[] = [
  // ── Legacy CI pipeline (pre-agentic-SDLC) ────────────────────────────
  '.github/workflows/oraculum-research.yml',
  '.github/workflows/archeologist.yml',
  '.github/workflows/prd.yml',
  '.github/workflows/label-on-merge.yml',
  '.github/workflows/notify-code-repos.yml',
  // ── B-PR1f: replaced by user-triggered label flow (B20) ──────────────
  '.github/workflows/pr-auto-label.yml',
  // ── B20 Phase 2 sweep: per-agent workflows + Looking Glass dispatch
  // make these obsolete. WHY + HOW are end-to-end on per-agent files;
  // WHAT lands in Phase 3 with its own per-agent file (code-design-
  // agent.yml). Until then, the WHAT pipeline simply doesn't run —
  // which is fine, since "Start What" is gated in Looking Glass.
  '.github/workflows/okr-bus.yml',
  '.github/workflows/reviewer-bus.yml',
  '.github/workflows/okr-state-machine.yml',
  '.github/workflows/design-bus.yml',
  '.github/workflows/drift-gate.yml',
  '.github/workflows/audit-validate.yml',
  // ── B24: self-critique in prd-agent.agent.md replaces separate
  // reviewer agents at PRD time. The reviewer workflows ship a no-op
  // dispatch loop now — useful only as dead weight + a bot-PR gate
  // trap. Pruned from any mesh repo on next Redeploy. Same for the
  // two reviewer .agent.md files — they're no longer in MESH_AGENTS
  // so the prune sweeps them out of any mesh that previously deployed
  // them.
  '.github/workflows/architect-reviewer.yml',
  '.github/workflows/security-reviewer.yml',
  '.github/agents/architect-reviewer.agent.md',
  '.github/agents/security-reviewer.agent.md',
];

