/**
 * D2 regression — `parseReviewsYaml` must parse the Information Risk pillar
 * from the `risk:` key the architecture-review-agent persona actually writes.
 *
 * The live records #216/#218/#220 (governance-mesh imdb-lite-application)
 * spell the third pillar `risk:` — plain, not `information-risk:`. Before the
 * fix the parser's variant list omitted `risk`, so every record silently lost
 * its Information Risk counts. The fixtures below are byte-copies of the live
 * reviews.yaml; the assertions pin all four pillars + the canonical drift
 * formula so the parser and `BarService.computeDriftScore` cannot drift apart.
 */
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('vscode', () => ({
  workspace: {
    getConfiguration: () => ({ get: () => undefined, update: () => Promise.resolve() }),
    onDidChangeConfiguration: () => ({ dispose: () => undefined }),
  },
  Disposable: class { dispose() { /* noop */ } },
  EventEmitter: class { event = () => ({ dispose: () => undefined }); fire = () => undefined; dispose = () => undefined; },
  Uri: { file: (p: string) => ({ fsPath: p }) },
  ConfigurationTarget: { Global: 1, Workspace: 2, WorkspaceFolder: 3 },
}));

import { BarService } from '../BarService';
import { GovernanceScorer } from '../GovernanceScorer';

// Byte-copy of the live govern-mesh reviews.yaml (#218 record), `risk:` key.
const LIVE_REVIEWS_YAML = `# Oraculum Review History — generated by MaintainabilityAI
reviews:
  - issue_url: "https://github.com/AliceNN-ucdenver/alicenn-ucdenver-governance-mesh/issues/218"
    issue_number: 218
    date: "2026-06-10"
    agent: copilot
    drift_score: 60
    pillars:
      architecture:
        findings: 3
        critical: 0
        high: 1
        medium: 2
        low: 0
      security:
        findings: 2
        critical: 1
        high: 1
        medium: 0
        low: 0
      risk:
        findings: 2
        critical: 0
        high: 1
        medium: 1
        low: 0
      operations:
        findings: 2
        critical: 0
        high: 0
        medium: 2
        low: 0
`;

describe('BarService.readReviews — D2 (information-risk / risk key)', () => {
  let tmpRoot: string;
  let barPath: string;
  let bar: BarService;

  beforeEach(() => {
    tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'bar-reviews-'));
    barPath = path.join(tmpRoot, 'bar');
    fs.mkdirSync(barPath, { recursive: true });
    bar = new BarService(new GovernanceScorer());
  });

  afterEach(() => {
    fs.rmSync(tmpRoot, { recursive: true, force: true });
  });

  it('parses all four pillars including the `risk:` Information Risk key', () => {
    fs.writeFileSync(path.join(barPath, 'reviews.yaml'), LIVE_REVIEWS_YAML);
    const reviews = bar.readReviews(barPath);
    expect(reviews).toBeDefined();
    expect(reviews).toHaveLength(1);

    const r = reviews![0];
    expect(r.issueNumber).toBe(218);
    expect(r.driftScore).toBe(60);

    // The canonical key is `information-risk` (the `risk:` variant normalizes
    // to it). All four pillars must be present.
    expect(Object.keys(r.pillars).sort()).toEqual(
      ['architecture', 'information-risk', 'operations', 'security'],
    );

    expect(r.pillars['information-risk']).toEqual({
      findings: 2, critical: 0, high: 1, medium: 1, low: 0,
    });
  });

  it('recomputes the drift score from the parsed counts (matches the record)', () => {
    fs.writeFileSync(path.join(barPath, 'reviews.yaml'), LIVE_REVIEWS_YAML);
    const r = bar.readReviews(barPath)![0];
    // 15·1(crit) + 5·(1+1+1)(high) + 2·(2+1+2)(med) = 15 + 15 + 10 = 40 → 60.
    expect(BarService.computeDriftScore(r.pillars)).toBe(r.driftScore);
  });

  it('still parses the explicit `information-risk:` spelling', () => {
    fs.writeFileSync(
      path.join(barPath, 'reviews.yaml'),
      LIVE_REVIEWS_YAML.replace('      risk:', '      information-risk:'),
    );
    const r = bar.readReviews(barPath)![0];
    expect(r.pillars['information-risk']).toEqual({
      findings: 2, critical: 0, high: 1, medium: 1, low: 0,
    });
  });
});
