/**
 * Court Recorder — CloudEvents v1.0 envelope emitter for the agentic-SDLC
 * audit chain. Wraps `audit-emitter`'s raw event payload in a CloudEvents
 * 1.0 envelope so the resulting JSONL is SIEM-compatible without further
 * transformation.
 *
 * Phase B-PR4 ships the emitter shape; agents will adopt it in their
 * `audit-emit-event` Skill backend (B-PR1a). Each line of
 * `okrs/<id>/audit/events/<run-id>.jsonl` is a fully-valid CloudEvents
 * envelope whose `data` property carries the original audit-event JSON.
 *
 * Spec: vscode-extension/design/agentic-sdlc.md §11 (Court Recorder).
 */
import * as crypto from 'node:crypto';

/**
 * Strictly the fields a CloudEvents v1.0 envelope requires. Optional
 * fields per the spec (datacontenttype, dataschema, subject, time) are
 * folded in via `CloudEventsOptional`.
 *
 * See https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md
 */
export interface CloudEventsEnvelope<T = Record<string, unknown>> {
  /** CloudEvents spec version. Fixed for our emitter. */
  specversion: '1.0';
  /** Reverse-DNS event-source identifier — e.g. `maintainabilityai/research-runner`. */
  source: string;
  /** Event type — maps to `audit-emitter` event_kind plus an `mai.` prefix. */
  type: string;
  /** Unique id — UUID v4 generated by the emitter. */
  id: string;
  /** ISO timestamp when the event was emitted. */
  time: string;
  /** MIME type of `data`. Always `application/json` for our emitter. */
  datacontenttype: 'application/json';
  /** OKR phase that contextualizes this event. */
  subject: string;
  /** The raw audit-emitter event payload. */
  data: T;
}

export interface CourtRecorderInput<T> {
  /** Reverse-DNS source identifier — e.g. `maintainabilityai/research-runner`. */
  source: string;
  /** Event kind from `audit-emitter` — wrapped into `mai.<kind>` for CE `type`. */
  eventKind: string;
  /** OKR phase (`why` | `how` | `what` | `setup` etc.) → goes in `subject`. */
  phase: string;
  /** The original audit-emitter event payload. Becomes `data`. */
  payload: T;
  /** Override timestamp (defaults to `new Date().toISOString()`). */
  time?: string;
  /** Override id (defaults to `crypto.randomUUID()`). */
  id?: string;
}

/**
 * Build a single CloudEvents v1.0 envelope around an audit-event payload.
 * Stateless + deterministic given an injected `id` + `time` — handy for
 * unit tests.
 */
export function buildCloudEventsEnvelope<T>(
  input: CourtRecorderInput<T>,
): CloudEventsEnvelope<T> {
  return {
    specversion: '1.0',
    source: input.source,
    type: `mai.${input.eventKind}`,
    id: input.id ?? crypto.randomUUID(),
    time: input.time ?? new Date().toISOString(),
    datacontenttype: 'application/json',
    subject: input.phase,
    data: input.payload,
  };
}

/**
 * Serialize an envelope to a single JSONL line (NO trailing newline; the
 * caller appends `\n` when writing). Throws if the envelope can't be
 * round-tripped through JSON.stringify — that signals a non-serializable
 * payload, which is a programmer bug, not a runtime condition.
 */
export function serializeCloudEventsEnvelope<T>(env: CloudEventsEnvelope<T>): string {
  return JSON.stringify(env);
}
